/**
 * Oil and Gas Reporting System (OGRS-API)
 * This is an api  to allows users to obtain infomation about the oil and gas wells database and generating a punch of related reposts such as wells count, insurance as well as production allocation funcationality
 *
 * OpenAPI spec version: 3.0
 * Contact: mohamed.wafa770@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FieldsBudgetAndActualRequest { 
    productionDate?: string;
    meleihaBudget?: number;
    meleihaActual?: number;
    meleihaPercentage?: number;
    agharActual?: number;
    agharBudget?: number;
    agharPercentage?: number;
    eastKanaysActual?: number;
    eastKanaysBudget?: number;
    eastKanysPercentage?: number;
    zarifActual?: number;
    zarifBudget?: number;
    zarifPercentage?: number;
    farasActual?: number;
    farasBudget?: number;
    farasPercentage?: number;
    ramlActual?: number;
    ramlBudget?: number;
    ramlPercentage?: number;
    westernDesertActual?: number;
    westernDesertBudget?: number;
    westernDesertPercentage?: number;
    ashrafiActual?: number;
    ashrafiBudget?: number;
    ashrafiPercentage?: number;
    agibaOilActual?: number;
    agibaOilBudget?: number;
    agibaOilPercentage?: number;
    salesGasActual?: number;
}