/**
 * Oil and Gas Reporting System (OGRS-API)
 * This is an api  to allows users to obtain infomation about the oil and gas wells database and generating a punch of related reposts such as wells count, insurance as well as production allocation funcationality
 *
 * OpenAPI spec version: 3.0
 * Contact: mohamed.wafa770@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from 'service_utils/encoder';

import { Observable }                                        from 'rxjs';

import { AllLabs } from '../model/allLabs';
import { AllLabsOfAWell } from '../model/allLabsOfAWell';
import { LabMeasurementRequest } from '../model/labMeasurementRequest';
import { LabMeasurementResponse } from '../model/labMeasurementResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from 'service_utils/variables';
import { Configuration }                                     from 'service_utils/configuration';


@Injectable()
export class LabService {

    protected basePath = 'http://www.ourcompany.com/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add a new lab Measurement
     * Add a new lab Measurement to well
     * @param body LabMeasurement object that needs to be added
     * @param wellId ID of lab to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addLabMeasurement(body: LabMeasurementRequest, wellId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public addLabMeasurement(body: LabMeasurementRequest, wellId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public addLabMeasurement(body: LabMeasurementRequest, wellId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public addLabMeasurement(body: LabMeasurementRequest, wellId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addLabMeasurement.');
        }

        if (wellId === null || wellId === undefined) {
            throw new Error('Required parameter wellId was null or undefined when calling addLabMeasurement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/wells/${encodeURIComponent(String(wellId))}/labs`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes a lab
     * Deletes a lab by its id
     * @param wellId Delete a lab in a well by its id
     * @param labId Delete a lab by its id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteLabById(wellId: number, labId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteLabById(wellId: number, labId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteLabById(wellId: number, labId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteLabById(wellId: number, labId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (wellId === null || wellId === undefined) {
            throw new Error('Required parameter wellId was null or undefined when calling deleteLabById.');
        }

        if (labId === null || labId === undefined) {
            throw new Error('Required parameter labId was null or undefined when calling deleteLabById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/wells/${encodeURIComponent(String(wellId))}/labs/${encodeURIComponent(String(labId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find labs between two dates
     * Returns labs between two dates
     * @param beginDate getting the daily actions that are of that date or after
     * @param endDate getting the daily actions that are of that date or after
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllLabs(beginDate?: string, endDate?: string, observe?: 'body', reportProgress?: boolean): Observable<AllLabs>;
    public getAllLabs(beginDate?: string, endDate?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllLabs>>;
    public getAllLabs(beginDate?: string, endDate?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllLabs>>;
    public getAllLabs(beginDate?: string, endDate?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (beginDate !== undefined && beginDate !== null) {
            queryParameters = queryParameters.set('beginDate', <any>beginDate);
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('endDate', <any>endDate);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AllLabs>('get',`${this.basePath}/wells/labs`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find labs between two dates
     * Returns labs between two dates
     * @param wellId ID of lab to return
     * @param beginDate getting the daily actions that are of that date or after
     * @param endDate getting the daily actions that are of that date or after
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllLabsInWell(wellId: number, beginDate?: string, endDate?: string, observe?: 'body', reportProgress?: boolean): Observable<AllLabsOfAWell>;
    public getAllLabsInWell(wellId: number, beginDate?: string, endDate?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllLabsOfAWell>>;
    public getAllLabsInWell(wellId: number, beginDate?: string, endDate?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllLabsOfAWell>>;
    public getAllLabsInWell(wellId: number, beginDate?: string, endDate?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (wellId === null || wellId === undefined) {
            throw new Error('Required parameter wellId was null or undefined when calling getAllLabsInWell.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (beginDate !== undefined && beginDate !== null) {
            queryParameters = queryParameters.set('beginDate', <any>beginDate);
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('endDate', <any>endDate);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AllLabsOfAWell>('get',`${this.basePath}/wells/${encodeURIComponent(String(wellId))}/labs`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find a certain lab on a certain well
     * Returns a certain lab on a certain well
     * @param wellId ID of lab to return
     * @param labId record Id of the lab measurements table
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLabByWellIdAndLabId(wellId: number, labId: number, observe?: 'body', reportProgress?: boolean): Observable<LabMeasurementResponse>;
    public getLabByWellIdAndLabId(wellId: number, labId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LabMeasurementResponse>>;
    public getLabByWellIdAndLabId(wellId: number, labId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LabMeasurementResponse>>;
    public getLabByWellIdAndLabId(wellId: number, labId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (wellId === null || wellId === undefined) {
            throw new Error('Required parameter wellId was null or undefined when calling getLabByWellIdAndLabId.');
        }

        if (labId === null || labId === undefined) {
            throw new Error('Required parameter labId was null or undefined when calling getLabByWellIdAndLabId.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<LabMeasurementResponse>('get',`${this.basePath}/wells/${encodeURIComponent(String(wellId))}/labs/${encodeURIComponent(String(labId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a lab Measurement
     * Update an existing lab Measurement in a well
     * @param body LabMeasurement object that needs to be updated
     * @param wellId ID of lab to return
     * @param labId record Id of the lab measurements table
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateLabMeasurement(body: LabMeasurementRequest, wellId: number, labId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateLabMeasurement(body: LabMeasurementRequest, wellId: number, labId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateLabMeasurement(body: LabMeasurementRequest, wellId: number, labId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateLabMeasurement(body: LabMeasurementRequest, wellId: number, labId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateLabMeasurement.');
        }

        if (wellId === null || wellId === undefined) {
            throw new Error('Required parameter wellId was null or undefined when calling updateLabMeasurement.');
        }

        if (labId === null || labId === undefined) {
            throw new Error('Required parameter labId was null or undefined when calling updateLabMeasurement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/wells/${encodeURIComponent(String(wellId))}/labs/${encodeURIComponent(String(labId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
